// Generates docs/SHOT_LIST.md and docs/CUE_SHEET.md from the config, so the
// paperwork can never drift from what the film actually renders.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import film from '../src/config/film.config';
import { buildSfx, voWindows } from '../src/lib/audioTimeline';
import { category, holeById } from '../src/lib/timeline';

const ROOT = join(import.meta.dirname, '..');
const ts = (n: number) => `${Math.floor(n / 60)}:${(n % 60).toFixed(1).padStart(4, '0')}`;
const vo = voWindows();
const labelOf = (id: string) => {
  const h = holeById.get(id)!;
  return h.kind === 'leak' ? category(h.leak).label : `${h.id} (rotating: ${h.cycle.map((c) => category(c).label).join(' / ')})`;
};

let shot = `# Shot list — ${film.title}\n\n_Generated from \`src/config/film.config.ts\` by \`npm run docs\`. Do not edit by hand._\n\n`;
shot += `${film.output.durationSeconds}s · ${film.output.fps}fps · master 3840×2160 · ${film.shots.length} shots\n\n`;
shot += `| Shot | In–Out | Dur | Scene | Lens | Camera | Action | Labels on screen | Narration over shot | Super |\n|---|---|---|---|---|---|---|---|---|---|\n`;
for (const s of film.shots) {
  const v = vo.filter((w) => w.start < s.end && w.end > s.start).map((w) => `${w.id}: “${w.text}”`).join('<br>');
  const sp = film.supers.filter((x) => x.start < s.end && x.end > s.start).map((x) => x.text).join('<br>');
  const labels = s.visible.map(labelOf).join('<br>');
  shot += `| **${s.id}** ${s.title} | ${ts(s.start)}–${ts(s.end)} | ${(s.end - s.start).toFixed(1)}s | ${s.scene} | ${s.lens} | ${s.camera} | ${s.action} | ${labels || '—'} | ${v || '—'} | ${sp || '—'} |\n`;
}
shot += `\n## Leak timeline\n\n| Hole | Category | Opens | Label | Sealed |\n|---|---|---|---|---|\n`;
for (const h of film.holes) shot += `| ${h.id} | ${labelOf(h.id)} | ${ts(h.opensAt)} | ${ts(h.labelAt)} | ${ts(h.sealsAt)} |\n`;
writeFileSync(join(ROOT, 'docs/SHOT_LIST.md'), shot);

let cue = `# Audio cue sheet — ${film.title}\n\n_Generated by \`npm run docs\`._\n\nMix priority: narration → key SFX → music. Music ducks ${film.audio.mix.duckDb} dB under narration (attack ${film.audio.mix.duckAttack}s / release ${film.audio.mix.duckRelease}s). Master to ${film.audio.mix.targetLufs} LUFS, ${film.audio.mix.truePeakDb} dBTP.\n\n`;
cue += `## Narration\n\n| ID | In | Must end by | Text |\n|---|---|---|---|\n`;
for (const w of film.narration) cue += `| ${w.id}${w.enabled ? '' : ' _(disabled)_'} | ${ts(w.start)} | ${ts(w.mustEndBy)} | ${w.text} |\n`;
cue += `\n## Music sections (ElevenLabs composition plan)\n\n| Section | In–Out | Direction |\n|---|---|---|\n`;
for (const m of film.audio.music.sections) cue += `| ${m.name} | ${ts(m.start)}–${ts(m.end)} | ${m.positive.join('; ')} — avoid: ${m.negative.join(', ')} |\n`;
cue += `\n## Key sound design cues\n\n| Time | Cue | Gain |\n|---|---|---|\n`;
for (const c of buildSfx().filter((c) => !c.id.startsWith('in-') && !c.id.startsWith('es-'))) cue += `| ${ts(c.at)} | ${c.key} (${c.id}) | ${c.gainDb.toFixed(0)} dB |\n`;
cue += `\nPlus procedural layers: inflow coin hits every ~${film.sfxProcedural.inflow.everySeconds}s (${film.sfxProcedural.inflow.from}–${film.sfxProcedural.inflow.to}s); escape impacts whose density scales with the number of open holes.\n`;
writeFileSync(join(ROOT, 'docs/CUE_SHEET.md'), cue);
console.log('docs/SHOT_LIST.md and docs/CUE_SHEET.md written');
